# Generated by Django 4.1.7 on 2023-03-07 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lab_eq_borrow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='item_borrow_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.borrow_statuses'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item_categories'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.departments'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.faculties'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.id_types'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.item_statuses'),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.departments'),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_faculty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.faculties'),
        ),
        migrations.AlterField(
            model_name='users',
            name='u_privilege',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='lab_eq_borrow.user_privileges'),
        ),
    ]
